[build]
  command = "npm run build"
  publish = "out"

# Environment variables
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect all paths to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' *.netlify.app; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src 'self' data: blob: *.netlify.app; font-src 'self' fonts.gstatic.com fonts.googleapis.com; connect-src 'self' *.netlify.app;"

# Cache static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"